site_name: Documentation technique Papillon
site_url: https://docs.getpapillon.xyz
repo_url: https://github.com/PapillonApp/docs
repo_name: PapillonApp/docs
edit_uri: edit/main/docs/
nav:
  - Accueil: 'index.md'
  - Designer :
    - Introduction : 'design/intro.md'
    - Charte Graphique :
      - Couleurs : 'design/color.md'
      - Polices d'écriture : 'design/font.md'
    - Ressources externe :
      - Charte grapique (PDF) : '../assets/design/Charte%20Graphique%20-%20Papillon%20(sept.%202023).pdf'
      - Figma (Public) : 'https://www.figma.com/file/BBRs6LrDJvKs79JIDk1h6M/Papillon-%F0%9F%A6%8B---v6-(PUBLIC)?type=design&node-id=291%3A766&mode=design&t=Asx54o7vvJwd1T7m-1'
  - Développer :
    - Introduction : 'development/intro.md'
    - Fonctionnement de l'app :
      - ENT : 'development/ent.md'
    - Environement de développement :
      - Développement iOS : 'development/app/ios.md'
      - Développement Android : 'development/app/android.md'
    - API utilisées pour Papillon :
        - Pawnote (compatible Pronote) : 'development/api/pawnote.md'
        - EcoleDirecte:
          - API: 'development/api/ed/api.md'
          - papillon-ed-core: 'development/api/ed/papillon.md'
        - Turboself:
          - API : 'development/api/ts/api.md'
          - papillon-turboself-core : 'development/api/ts/papillon.md'
  - Contribuer :
    - Introduction : 'contribute/intro.md'
    - Tester les nouveautés :
      - Programme bêta : 'contribute/beta.md'
      - Rapporter des problèmes : 'contribute/reporting-issues.md'
    - Soumettre vos modifications : 
      - Pull Request : 'contribute/pull-request.md'
      - Parution dans l'app finale : 'contribute/final-step.md'
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  language: fr
  logo: assets/beta.png
  favicon: assets/beta.png
  font:
    text: Noto Sans
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate 
    - navigation.sections
plugins:
  - search
  - swagger-ui-tag
  - git-revision-date-localized:
      locale: fr
      type: timeago
      fallback_to_build_date: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PapillonApp/Papillon
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/thepapillonapp/
    - icon: fontawesome/brands/discord
      link: https://discord.getpapillon.xyz/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
extra_css:
  - stylesheets/extra.css
